app:
  frontend:
    domain: "photogram.local"
    port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS