app:
  frontend:
    domain: "localhost"
    port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        format_sql: true  # Formatea las consultas para que se vean más legibles
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE